# The Docker image that will be used to build your app

image: python:3.11
# Functions that should be executed before the build script is run
before_script:
  - pip install ".[docs]"
pages:
  script:
    - make -C docs html
    - mv docs/_build/html/ public
  pages:
    path_prefix: "$CI_COMMIT_BRANCH"
    expire_in: never
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  only:
    # This ensures that only pushes to a branch will trigger
    - branches
